# Generated by Django 2.0.10 on 2019-02-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_imgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imgs',
            new_name='Images',
        ),
    ]
